services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-false}
      WATCHTOWER_TIMEOUT: ${WATCHTOWER_TIMEOUT:-10s}
      WATCHTOWER_RUN_ONCE: "true"
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels: &cron-labels
        swarm.cronjob.enable: "true"
        swarm.cronjob.skip-running: "true"
        swarm.cronjob.schedule: ${SCHEDULE}

  gantry:
    image: shizunge/gantry:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      GANTRY_NODE_NAME: "{{.Node.Hostname}}"
      GANTRY_SLEEP_SECONDS: "0"
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: none
      labels:
        <<: *cron-labels
        swarm.cronjob.schedule: "${SCHEDULE_GANTRY:-${SCHEDULE}}" # If you want to offset them

  swarm-cronjob:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
