services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ:-UTC}
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-true}
      WATCHTOWER_TIMEOUT: ${WATCHTOWER_TIMEOUT:-60s}
      WATCHTOWER_RUN_ONCE: "true"
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels: &cron-labels
        swarm.cronjob.enable: "true"
        swarm.cronjob.skip-running: "true"
        swarm.cronjob.schedule: ${SCHEDULE}

  gantry:
    image: shizunge/gantry:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ:-UTC}
      GANTRY_NODE_NAME: "{{.Node.Hostname}}"
      GANTRY_SLEEP_SECONDS: "0"
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: none
      labels:
        <<: *cron-labels
        swarm.cronjob.schedule: ${SCHEDULE_GANTRY:-$SCHEDULE}

  swarm-cronjob:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ:-UTC}
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
